CREATE TABLE PRIDECLUS.PROTEOMES AS
SELECT
UNIQUE
  PSM.SEQUENCE SEQUENCE,
  PSM.MODIFICATIONS MODS,
  ASSAY.TAXID TAXID,
  ASSAY.ASSAY_ACCESSION ASSAY_ACCESSION,
  ASSAY.PROJECT_ACCESSION PROJECT_ACCESSION,
  SPECTRUM_CLUSTER.CLUSTER_PK CLUSTER_ID
FROM
  (SELECT
    CLUSTER_PK FROM SPECTRUM_CLUSTER
    WHERE SPECTRUM_CLUSTER.QUALITY = 1) SPECTRUM_CLUSTER,
  (SELECT
    RANK,
    CLUSTER_HAS_PSM.CLUSTER_FK,
    CLUSTER_HAS_PSM.PSM_FK
    FROM CLUSTER_HAS_PSM
    WHERE CLUSTER_HAS_PSM.RANK = 1.1) CLUSTER_HAS_PSM,
  PSM,
  (SELECT
    ASSAY.ASSAY_PK,
    ASSAY.TAXONOMY_ID TAXID,
    ASSAY.ASSAY_ACCESSION ASSAY_ACCESSION,
    ASSAY.PROJECT_ACCESSION PROJECT_ACCESSION FROM ASSAY
    WHERE ASSAY.MULTI_SPECIES = 0) ASSAY
WHERE SPECTRUM_CLUSTER.CLUSTER_PK = CLUSTER_HAS_PSM.CLUSTER_FK
AND CLUSTER_HAS_PSM.PSM_FK      = PSM.PSM_PK
AND PSM.ASSAY_FK                = ASSAY.ASSAY_PK
ORDER BY
  PSM.SEQUENCE,
  PSM.MODIFICATIONS,
  ASSAY.TAXID,
  SPECTRUM_CLUSTER.CLUSTER_PK;

CREATE INDEX PRIDECLUS.COMB_IDX ON PRIDECLUS.PROTEOMES (SEQUENCE, TAXID, MODS, CLUSTER_ID, ASSAY_ACCESSION, PROJECT_ACCESSION) TABLESPACE PRIDECLUS_IND ;
CREATE INDEX PRIDECLUS.PROTEOMES_SEQUENCE_IDX ON PRIDECLUS.PROTEOMES (SEQUENCE) TABLESPACE PRIDECLUS_IND;

SELECT COUNT(*) FROM PROTEOMES; /*8558261*/

-- DROP TABLE PRIDECLUS.PROTEOMES CASCADE CONSTRAINTS ;