-- Execute in proteomes database
CREATE TABLE PRIDEPROT.PROTEOMES AS
SELECT
UNIQUE
  PSM.SEQUENCE SEQUENCE,
  PSM.MODIFICATIONS MODS,
  ASSAY.TAXID TAXID,
  ASSAY.ASSAY_ACCESSION ASSAY_ACCESSION,
  ASSAY.PROJECT_ACCESSION PROJECT_ACCESSION,
  SPECTRUM_CLUSTER.CLUSTER_PK CLUSTER_ID
FROM
  (SELECT
    CLUSTER_PK FROM PRIDECLUS.SPECTRUM_CLUSTER
    WHERE SPECTRUM_CLUSTER.QUALITY = 1) SPECTRUM_CLUSTER,
  (SELECT
    RANK,
    CLUSTER_FK,
    PSM_FK
    FROM PRIDECLUS.CLUSTER_HAS_PSM
    WHERE CLUSTER_HAS_PSM.RANK = 1.1) CLUSTER_HAS_PSM,
  PRIDECLUS.PSM PSM,
  (SELECT
    ASSAY.ASSAY_PK,
    ASSAY.TAXONOMY_ID TAXID,
    ASSAY.ASSAY_ACCESSION ASSAY_ACCESSION,
    ASSAY.PROJECT_ACCESSION PROJECT_ACCESSION FROM PRIDECLUS.ASSAY
    WHERE ASSAY.MULTI_SPECIES = 0) ASSAY
WHERE SPECTRUM_CLUSTER.CLUSTER_PK = CLUSTER_HAS_PSM.CLUSTER_FK
  AND CLUSTER_HAS_PSM.PSM_FK      = PSM.PSM_PK
  AND PSM.ASSAY_FK                = ASSAY.ASSAY_PK
ORDER BY
  PSM.SEQUENCE,
  PSM.MODIFICATIONS,
  ASSAY.TAXID,
  SPECTRUM_CLUSTER.CLUSTER_PK;

CREATE INDEX COMB_IDX ON PRIDEPROT.PROTEOMES (SEQUENCE, TAXID, MODS, CLUSTER_ID, ASSAY_ACCESSION, PROJECT_ACCESSION) TABLESPACE PRIDEPROT_IND ;
CREATE INDEX PROTEOMES_SEQUENCE_IDX ON PRIDEPROT.PROTEOMES (SEQUENCE) TABLESPACE PRIDEPROT_IND;

-- SELECT COUNT(*) FROM PROTEOMES;
-- DROP TABLE PRIDEPROT.PROTEOMES CASCADE CONSTRAINTS ;